name: hotel_booking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  envied: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  hive: ^4.0.0-dev.2
  http: ^1.2.2
  injectable: ^2.5.0
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  slang: ^4.4.0
  slang_flutter: ^4.4.0
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  envied_generator: ^1.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  slang_build_runner: ^4.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
