name: Flutter CI/CD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Manually install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Start Android emulator
        run: |
          echo "Setting up Android emulator"
          sudo $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-31;default;x86_64"
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-31;default;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-snapshot -noaudio -no-window &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Start Appium Server
        run: |
          echo "Installing Appium"
          npm install -g appium
          echo "Starting Appium Server"
          appium --log-level info &

      - name: Run integration tests on Android
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/overview_test.dart

      - name: Run integration tests on iOS
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/navbar_test.dart -d iOS

  flutter-tests-matrix:
    runs-on: macos-latest
    strategy:
      matrix:
        flutter-version: ['3.13.0', 3.7.0, 3.10.0]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Manually install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Start Android emulator
        run: |
          echo "Setting up Android emulator"
          sudo $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-31;default;x86_64"
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-31;default;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-snapshot -noaudio -no-window &
          adb wait-for-device

      - name: Start Appium Server
        run: |
          echo "Installing Appium"
          npm install -g appium
          echo "Starting Appium Server"
          appium --log-level info &

      - name: Run integration tests on Android
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/overview_test.dart

      - name: Run integration tests on iOS
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/navbar_test.dart -d iOS
