name: Running CI for hotel search
on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          cache: true

      - name: Get Flutter packages
        run: flutter pub get

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_3
          avd-name: test-emulator
          disable-animations: true
          script: echo "Emulator started"

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device shell 'while [[ "$(getprop sys.boot_completed)" != "1" ]]; do sleep 1; done'
          adb devices

      - name: Debug Emulator State
        run: |
          adb shell getprop
          adb shell pm list packages

      - name: Grant Permissions
        run: adb shell pm grant com.example.yourapp android.permission.WRITE_EXTERNAL_STORAGE

      - name: Run integration tests
        run: flutter test integration_test -d emulator-5554